name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  loc_generator:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/lang/