name: loc_generator
description: A powerful Dart package for generating localization files and constants for Flutter applications. Automatically generates type-safe locale keys and translation files from a master language configuration.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  watcher: ^1.1.2
# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
